server:
  port: 8090

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://192.168.1.7:5432/todo_db
    username: postgres
    password: postgres